Menghitung matriks normalisasi dan nilai eigen dari tabel data parameter

In [3]:
import numpy as np

#tabel rating
data1 = np.mat("1 4 2 3 4 4; \
               0.25 1 2 3 3 3; \
               0.5 0.5 1 4 3 4; \
               0.33 0.33 0.25 1 3 4; \
               0.25 0.33 0.33 0.33 1 2; \
               0.25 0.33 0.25 0.25 0.5 1")

print("Matriks Data:\n", data1)

max_values = np.sum(data1, axis=0)

normalized_matrix1 = data1 / max_values

print("\nMatriks Normalisasi:")
print(np.round(normalized_matrix1, 3))

num_parameters = 6
eigen_values1 = np.sum(normalized_matrix1, axis=1)/num_parameters
print("\nVektor Eigen: ")
print(np.round(eigen_values1, 3))


Matriks Data:
 [[1.   4.   2.   3.   4.   4.  ]
 [0.25 1.   2.   3.   3.   3.  ]
 [0.5  0.5  1.   4.   3.   4.  ]
 [0.33 0.33 0.25 1.   3.   4.  ]
 [0.25 0.33 0.33 0.33 1.   2.  ]
 [0.25 0.33 0.25 0.25 0.5  1.  ]]

Matriks Normalisasi:
[[0.388 0.616 0.343 0.259 0.276 0.222]
 [0.097 0.154 0.343 0.259 0.207 0.167]
 [0.194 0.077 0.172 0.345 0.207 0.222]
 [0.128 0.051 0.043 0.086 0.207 0.222]
 [0.097 0.051 0.057 0.028 0.069 0.111]
 [0.097 0.051 0.043 0.022 0.034 0.056]]

Vektor Eigen: 
[[0.351]
 [0.204]
 [0.203]
 [0.123]
 [0.069]
 [0.05 ]]


In [25]:
#tidak dii input
import numpy as np

#tabel rating
data = np.mat("1 3 4 2 3 1; \
               0.33 1 2 1 2 1; \
               0.25 0.5 1 3 4 2; \
               0.5 1 0.33 1 1 1; \
               0.33 0.5 0.25 1 1 2; \
               1 1 0.5 1 0.5 1")

print("Matriks Data:\n", data)

max_values = np.sum(data, axis=0)

normalized_matrix2 = data / max_values

print("\nMatriks Normalisasi:")
print(np.round(normalized_matrix2, 3))

num_parameters = 6
eigen_values2 = np.sum(normalized_matrix2, axis=1)/num_parameters
print("\nVektor Eigen: ")
print(np.round(eigen_values2, 3))


Matriks Data:
 [[1.   3.   4.   2.   3.   1.  ]
 [0.33 1.   2.   1.   2.   1.  ]
 [0.25 0.5  1.   3.   4.   2.  ]
 [0.5  1.   0.33 1.   1.   1.  ]
 [0.33 0.5  0.25 1.   1.   2.  ]
 [1.   1.   0.5  1.   0.5  1.  ]]

Matriks Normalisasi:
[[0.293 0.429 0.495 0.222 0.261 0.125]
 [0.097 0.143 0.248 0.111 0.174 0.125]
 [0.073 0.071 0.124 0.333 0.348 0.25 ]
 [0.147 0.143 0.041 0.111 0.087 0.125]
 [0.097 0.071 0.031 0.111 0.087 0.25 ]
 [0.293 0.143 0.062 0.111 0.043 0.125]]

Vektor Eigen: 
[[0.304]
 [0.15 ]
 [0.2  ]
 [0.109]
 [0.108]
 [0.13 ]]


Perbandian Kriteria E-Commerce

1. Harga


In [27]:
import numpy as np

#tabel rating
data = np.mat("1 2 1 2 2 1; \
               0.5 1 1 2 1 1; \
               1 1 1 2 1 2; \
               0.5 0.5 0.5 1 2 1; \
               0.5 1 1 0.5 1 1; \
               1 1 0.5 1 1 1")

print("Matriks Data:\n", data)

max_values = np.sum(data, axis=0)

normalized_matrix3 = data / max_values

print("\nMatriks Normalisasi:")
print(np.round(normalized_matrix3, 3))

num_parameters = 6
eigen_values3 = np.sum(normalized_matrix3, axis=1)/num_parameters
print("\nVektor Eigen Eigen: ")
print(np.round(eigen_values3, 3))


Matriks Data:
 [[1.  2.  1.  2.  2.  1. ]
 [0.5 1.  1.  2.  1.  1. ]
 [1.  1.  1.  2.  1.  2. ]
 [0.5 0.5 0.5 1.  2.  1. ]
 [0.5 1.  1.  0.5 1.  1. ]
 [1.  1.  0.5 1.  1.  1. ]]

Matriks Normalisasi:
[[0.222 0.308 0.2   0.235 0.25  0.143]
 [0.111 0.154 0.2   0.235 0.125 0.143]
 [0.222 0.154 0.2   0.235 0.125 0.286]
 [0.111 0.077 0.1   0.118 0.25  0.143]
 [0.111 0.154 0.2   0.059 0.125 0.143]
 [0.222 0.154 0.1   0.118 0.125 0.143]]

Vektor Eigen Eigen: 
[[0.226]
 [0.161]
 [0.204]
 [0.133]
 [0.132]
 [0.144]]


2. Gratis  ongkir

In [28]:
import numpy as np

#tabel rating
data = np.mat("1 2 1 2 1 2; \
               0.5 1 2 1 2 2; \
               1 0.5 1 2 1 2; \
               0.5 1 0.5 1 1 2; \
               1 0.5 1 1 1 2; \
               0.5 0.5 0.5 0.5 0.5 1")

print("Matriks Data:\n", data)

max_values = np.sum(data, axis=0)

normalized_matrix4 = data / max_values

print("\nMatriks Normalisasi:")
print(np.round(normalized_matrix4, 3))

num_parameters = 6
eigen_values4 = np.sum(normalized_matrix4, axis=1)/num_parameters
print("\nVektor Eigen: ")
print(np.round(eigen_values4, 3))


Matriks Data:
 [[1.  2.  1.  2.  1.  2. ]
 [0.5 1.  2.  1.  2.  2. ]
 [1.  0.5 1.  2.  1.  2. ]
 [0.5 1.  0.5 1.  1.  2. ]
 [1.  0.5 1.  1.  1.  2. ]
 [0.5 0.5 0.5 0.5 0.5 1. ]]

Matriks Normalisasi:
[[0.222 0.364 0.167 0.267 0.154 0.182]
 [0.111 0.182 0.333 0.133 0.308 0.182]
 [0.222 0.091 0.167 0.267 0.154 0.182]
 [0.111 0.182 0.083 0.133 0.154 0.182]
 [0.222 0.091 0.167 0.133 0.154 0.182]
 [0.111 0.091 0.083 0.067 0.077 0.091]]

Vektor Eigen: 
[[0.226]
 [0.208]
 [0.18 ]
 [0.141]
 [0.158]
 [0.087]]


3. Review & Rating

In [29]:

import numpy as np

#tabel rating
data = np.mat("1 1 1 2 2 1; \
               1 1 2 1 2 1; \
               1 0.5 1 2 1 2; \
               0.5 1 0.5 1 1 1; \
               0.5 0.5 1 1 1 2; \
               1 1 0.5 1 0.5 1")

print("Matriks Data:\n", data)

max_values = np.sum(data, axis=0)

normalized_matrix5 = data / max_values

print("\nMatriks Normalisasi:")
print(np.round(normalized_matrix5, 3))

num_parameters = 6
eigen_values5 = np.sum(normalized_matrix5, axis=1)/num_parameters
print("\nVektor Eigen: ")
print(np.round(eigen_values5, 3))


Matriks Data:
 [[1.  1.  1.  2.  2.  1. ]
 [1.  1.  2.  1.  2.  1. ]
 [1.  0.5 1.  2.  1.  2. ]
 [0.5 1.  0.5 1.  1.  1. ]
 [0.5 0.5 1.  1.  1.  2. ]
 [1.  1.  0.5 1.  0.5 1. ]]

Matriks Normalisasi:
[[0.2   0.2   0.167 0.25  0.267 0.125]
 [0.2   0.2   0.333 0.125 0.267 0.125]
 [0.2   0.1   0.167 0.25  0.133 0.25 ]
 [0.1   0.2   0.083 0.125 0.133 0.125]
 [0.1   0.1   0.167 0.125 0.133 0.25 ]
 [0.2   0.2   0.083 0.125 0.067 0.125]]

Vektor Eigen: 
[[0.201]
 [0.208]
 [0.183]
 [0.128]
 [0.146]
 [0.133]]


4. Jumlah Produk Terjual

In [30]:
import numpy as np

#tabel rating
data = np.mat("1 2 1 2 2 1; \
               0.5 1 2 1 2 1; \
               1 0.5 1 2 1 2; \
               0.5 1 0.5 1 1 1; \
               0.5 0.5 1 1 1 2; \
               1 1 0.5 1 0.5 1")

print("Matriks Data:\n", data)

max_values = np.sum(data, axis=0)

normalized_matrix6 = data / max_values

print("\nMatriks Normalisasi:")
print(np.round(normalized_matrix6, 3))

num_parameters = 6
eigen_values6 = np.sum(normalized_matrix6, axis=1)/num_parameters
print("\nVektor Eigen: ")
print(np.round(eigen_values6, 3))


Matriks Data:
 [[1.  2.  1.  2.  2.  1. ]
 [0.5 1.  2.  1.  2.  1. ]
 [1.  0.5 1.  2.  1.  2. ]
 [0.5 1.  0.5 1.  1.  1. ]
 [0.5 0.5 1.  1.  1.  2. ]
 [1.  1.  0.5 1.  0.5 1. ]]

Matriks Normalisasi:
[[0.222 0.333 0.167 0.25  0.267 0.125]
 [0.111 0.167 0.333 0.125 0.267 0.125]
 [0.222 0.083 0.167 0.25  0.133 0.25 ]
 [0.111 0.167 0.083 0.125 0.133 0.125]
 [0.111 0.083 0.167 0.125 0.133 0.25 ]
 [0.222 0.167 0.083 0.125 0.067 0.125]]

Vektor Eigen: 
[[0.227]
 [0.188]
 [0.184]
 [0.124]
 [0.145]
 [0.131]]


5. Keaslian Produk

In [31]:
import numpy as np

#tabel rating
data = np.mat("1 2 1 2 2 1; \
               0.5 1 2 1 1 1; \
               1 0.5 1 2 1 1; \
               0.5 1 0.5 1 2 1; \
               0.5 1 1 0.5 1 2; \
               1 1 1 1 0.5 1")

print("Matriks Data:\n", data)

max_values = np.sum(data, axis=0)

normalized_matrix7 = data / max_values

print("\nMatriks Normalisasi:")
print(np.round(normalized_matrix7, 3))

num_parameters = 6
eigen_values7 = np.sum(normalized_matrix7, axis=1)/num_parameters
print("\nVektor Eigen: ")
print(np.round(eigen_values7, 3))


Matriks Data:
 [[1.  2.  1.  2.  2.  1. ]
 [0.5 1.  2.  1.  1.  1. ]
 [1.  0.5 1.  2.  1.  1. ]
 [0.5 1.  0.5 1.  2.  1. ]
 [0.5 1.  1.  0.5 1.  2. ]
 [1.  1.  1.  1.  0.5 1. ]]

Matriks Normalisasi:
[[0.222 0.308 0.154 0.267 0.267 0.143]
 [0.111 0.154 0.308 0.133 0.133 0.143]
 [0.222 0.077 0.154 0.267 0.133 0.143]
 [0.111 0.154 0.077 0.133 0.267 0.143]
 [0.111 0.154 0.154 0.067 0.133 0.286]
 [0.222 0.154 0.154 0.133 0.067 0.143]]

Vektor Eigen: 
[[0.227]
 [0.164]
 [0.166]
 [0.147]
 [0.151]
 [0.145]]


6. Skala Toko

In [32]:
import numpy as np

#tabel rating
data = np.mat("1 2 2 2 2 2; \
               0.5 1 2 2 1 1; \
               0.5 0.5 1 2 1 1; \
               0.5 0.5 0.5 1 1 1; \
               0.5 1 1 1 1 1; \
               0.5 1 1 1 1 1")

print("Matriks Data:\n", data)

max_values = np.sum(data, axis=0)

normalized_matrix8 = data / max_values

print("\nMatriks Normalisasi:")
print(np.round(normalized_matrix8, 3))

num_parameters = 6
eigen_values8 = np.sum(normalized_matrix8, axis=1)/num_parameters
print("\nVektor Eigen: ")
print(np.round(eigen_values8, 3))


Matriks Data:
 [[1.  2.  2.  2.  2.  2. ]
 [0.5 1.  2.  2.  1.  1. ]
 [0.5 0.5 1.  2.  1.  1. ]
 [0.5 0.5 0.5 1.  1.  1. ]
 [0.5 1.  1.  1.  1.  1. ]
 [0.5 1.  1.  1.  1.  1. ]]

Matriks Normalisasi:
[[0.286 0.333 0.267 0.222 0.286 0.286]
 [0.143 0.167 0.267 0.222 0.143 0.143]
 [0.143 0.083 0.133 0.222 0.143 0.143]
 [0.143 0.083 0.067 0.111 0.143 0.143]
 [0.143 0.167 0.133 0.111 0.143 0.143]
 [0.143 0.167 0.133 0.111 0.143 0.143]]

Vektor Eigen: 
[[0.28 ]
 [0.181]
 [0.145]
 [0.115]
 [0.14 ]
 [0.14 ]]


In [5]:
#mencari nilai priority vector

priority_vector = (data1 * eigen_values1)/num_parameters
print("\nNilai vektor prioritas: " ,priority_vector)


Nilai vektor prioritas:  [[0.4032408 ]
 [0.23731636]
 [0.22995965]
 [0.12745272]
 [0.07203043]
 [0.05355711]]


In [9]:
import numpy as np

#tabel rating
data1 = np.mat("1 4 2 3 4 4; \
               0.25 1 2 3 3 3; \
               0.5 0.5 1 4 3 4; \
               0.33 0.33 0.25 1 3 4; \
               0.25 0.33 0.33 0.33 1 2; \
               0.25 0.33 0.25 0.25 0.5 1")

print("Matriks Data:\n", data1)

max_values = np.sum(data1, axis=0)

normalized_matrix1 = data1 / max_values

print("\nMatriks Normalisasi:")
print(np.round(normalized_matrix1, 3))

num_parameters = 6
eigen_values1 = np.sum(normalized_matrix1, axis=1)/num_parameters
print("\nVektor Eigen: ")
print(np.round(eigen_values1, 3))


Matriks Data:
 [[1.   4.   2.   3.   4.   4.  ]
 [0.25 1.   2.   3.   3.   3.  ]
 [0.5  0.5  1.   4.   3.   4.  ]
 [0.33 0.33 0.25 1.   3.   4.  ]
 [0.25 0.33 0.33 0.33 1.   2.  ]
 [0.25 0.33 0.25 0.25 0.5  1.  ]]

Matriks Normalisasi:
[[0.388 0.616 0.343 0.259 0.276 0.222]
 [0.097 0.154 0.343 0.259 0.207 0.167]
 [0.194 0.077 0.172 0.345 0.207 0.222]
 [0.128 0.051 0.043 0.086 0.207 0.222]
 [0.097 0.051 0.057 0.028 0.069 0.111]
 [0.097 0.051 0.043 0.022 0.034 0.056]]

Vektor Eigen: 
[[0.351]
 [0.204]
 [0.203]
 [0.123]
 [0.069]
 [0.05 ]]

Nilai Lamda Max:  [[6.74134242]]


In [14]:
# function to calculate product of 2 matrices
def matrix_product(mat1, mat2):
    result = np.zeros((6, 1))
    for i in range(6):
        for j in range(1):
            for k in range(6):
                result[i][j] += mat1[i][k] * mat2[k][j]
    return result

# matrix A with dimensions 6x6
A = np.array([[1, 2, 3, 4, 5, 6],
              [7, 8, 9, 10, 11, 12],
              [13, 14, 15, 16, 17, 18],
              [19, 20, 21, 22, 23, 24],
              [25, 26, 27, 28, 29, 30],
              [31, 32, 33, 34, 35, 36]])

# matrix B with dimensions 6x1
B = np.array([[2],
              [3],
              [4],
              [5],
              [6],
              [7]])

# calculating product of matrix A and matrix B
result = matrix_product(A, B)

print("\nResult of multiplication of matrices A and B:\n", result)


Result of multiplication of matrices A and B:
 [[112.]
 [274.]
 [436.]
 [598.]
 [760.]
 [922.]]


In [45]:
#data diambil dari tabel parameter (data 1)
data = np.array([[1. , 4. , 2. , 3. , 4. , 4. ],
                 [0.25, 1. , 2. , 3. , 3. , 3. ],
                 [0.5 , 0.5, 1. , 4. , 3. , 4. ],
                 [0.33, 0.33, 0.25, 1. , 3. , 4. ],
                 [0.25, 0.33, 0.33, 0.33, 1. , 2. ],
                 [0.25, 0.33, 0.25, 0.25, 0.5, 1. ]])

#priority vector merupakan vektor eigen yang didapat dari tabel parameter
priority_vector = np.array([[0.351,0.204, 0.203, 0.123, 0.069, 0.05 ]])

hasil_matriks = np.multiply(data, priority_vector)

sum_horizontal = np.sum(hasil_matriks, axis=1)

total_sum = np.sum(sum_horizontal/priority_vector) 

lambda_maks = total_sum / num_parameters

CI = (lambda_maks - num_parameters)/(num_parameters - 1)

RI = 1.24
CR = CI / RI

print("\n",hasil_matriks)
print("\n",sum_horizontal)
print("\n",total_sum)
print("\nThe lambda maximum is: ", lambda_maks)
print("\nCI: ", CI)
print("\nCR: ", CR)
print("\nKarena CR < 0.1 berarti referensi data dummy adalah konsisten")


 [[0.351   0.816   0.406   0.369   0.276   0.2    ]
 [0.08775 0.204   0.406   0.369   0.207   0.15   ]
 [0.1755  0.102   0.203   0.492   0.207   0.2    ]
 [0.11583 0.06732 0.05075 0.123   0.207   0.2    ]
 [0.08775 0.06732 0.06699 0.04059 0.069   0.1    ]
 [0.08775 0.06732 0.05075 0.03075 0.0345  0.05   ]]

 [2.418   1.42375 1.3795  0.7639  0.43165 0.32107]

 39.55138826515894

The lambda maximum is:  6.591898044193157

CI:  0.11837960883863144

CR:  0.09546742648276729

Karena CR < 0.1 berarti referensi data dummy adalah konsisten
